
### Create a Project with a User

POST http://localhost:8088/projects
Content-Type: application/x-www-form-urlencoded

projectTitle=Some Project Title&projectId={{projectId}}&creatorId={{user_id_Ivan}}&statusName={{statusInProgress}}&statusColor={{firstColor}}

### Get a Project view

GET http://localhost:8088/projects/{{projectId}}

### Add second Status

POST http://localhost:8088/projects/{{projectId}}/status?statusName={{statusInProgress}}&statusColor={{secondColor}}

### Add a Member to the Project

POST http://localhost:8088/projects/{{projectId}}/members?userId={{user_id_John}}

### Get all Statuses of a Project

GET http://localhost:8088/projects/{{projectId}}/statuses

### Delete the first Status

DELETE http://localhost:8088/projects/{{projectId}}/status?statusName={{statusInProgress}}&statusColor={{firstColor}}

### Get all Members of a Project

GET http://localhost:8088/projects/{{projectId}}/members

###
