
### Create a Task of a Project

POST http://localhost:8088/tasks
Content-Type: application/x-www-form-urlencoded

taskId={{taskId_1}}&projectId={{projectId}}&taskName=First task&statusName={{statusInProgress}}&statusColor={{firstColor}}

### Change the Task Name

PUT http://localhost:8088/tasks/{{taskId_1}}/name?taskName=Changed name

### Change the Task Status

PUT http://localhost:8088/tasks/{{taskId_1}}/status?statusName={{statusInProgress}}&statusColor={{secondColor}}

### Add an Executor to the task

POST http://localhost:8088/tasks/{{taskId_1}}/executors?userId={{user_id_John}}

### Get a Task view

GET http://localhost:8088/tasks/{{taskId_1}}

### Get all Executors of a task

GET http://localhost:8088/tasks/{{taskId_1}}/executors

### Get all Members of a task project

GET http://localhost:8088/tasks/{{taskId_1}}/project-members

### Get all Statuses of a task project

GET http://localhost:8088/tasks/{{taskId_1}}/statuses

###
