POST http://localhost:8080/users/Andrei?userPassword=123abc456

> {%
client.global.clearAll();
client.global.set("userId", response.body.userId);
client.log("userId: " + client.global.get("userId"));
%}

###

GET http://localhost:8080/users/{{userId}}

###
