
### Create user Andrei

POST http://localhost:8080/users/Andrei?userPassword=123abc456

> {%
client.global.clearAll();
client.global.set("userAndreiId", response.body.userId);
client.log("userAndreiId: " + client.global.get("userAndreiId"));
%}

### Create user Sergei

POST http://localhost:8080/users/Sergei?userPassword=123abc456

> {%
client.global.set("userSergeiId", response.body.userId);
client.log("userSergeiId: " + client.global.get("userSergeiId"));
%}

###

